# Generated by Django 3.2.3 on 2021-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
