# Generated by Django 3.2.3 on 2021-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_auto_20210930_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/img/profiles/avatar-07.jpg', null=True, upload_to='static/profile'),
        ),
    ]
